config/routes.rb
Rails.application.routes.draw do
  resources :homes, only: [:index, :show]
  resources :orders
  root "homes#index"
  
  devise_for :admins
  match "/admins/products/delete_image/:id" => "admins/products#delete_image", via: :get
  namespace :admins do
    namespace :products do
      post 'csv_upload'
    end
  end

  namespace :admins do
    resources :products
    resources :categories
    resources :orders 
  end

end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style=background-color:#00FFAE>
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Inw-sheep</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <% if admin_signed_in? %>
            <li class="nav-item">
                <a class="navbar-text" >Welcome, <%= current_admin.email %>!</a>
            </li>
            </li class="nav-item">
                <%= link_to 'All orders', admins_orders_path, class: 'nav-link'%>
            </li>
            <li class="nav-item">
                <%= link_to 'Sign out', destroy_admin_session_path, method: :delete, class: 'nav-link'%>
            </li>
        <% else %>
            <li class="nav-item">
                <%= link_to 'Register', new_admin_registration_path, class: 'nav-link'%>
            </li>
            <li class="nav-item">
                <%= link_to 'Sign in', new_admin_session_path, class: 'nav-link'%>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>