config/routes.rb
Rails.application.routes.draw do
  resources :homes, only: [:index, :show]
  resources :orders
  root "homes#index"
  
  devise_for :admins
  match "/admins/products/delete_image/:id" => "admins/products#delete_image", via: :get
  namespace :admins do
    namespace :products do
      post 'csv_upload'
    end
  end

  namespace :admins do
    resources :products
    resources :categories
    resources :orders 
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def index
        @products = Product.all
      end
      
      def show
        @product = Product.find(params[:id])
      end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<% if admin_signed_in? %>
  <%= link_to 'Go to admin mode', admins_products_path %>
<% end %>

<br>
<br>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Primary Image</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td> <% if product.primary_image.attached? %>
                <%= image_tag product.primary_image, class: "img-thumbnail", style: "max-height: 10rem;"%> 
                  <% end %>
        </td>
        <td><%= product.title %></td>
        <td><%= link_to 'Show', home_path(product) %></td>
        <td>
          <%= link_to new_order_path, class: "btn btn-info btn-lg" do  %>
            <span class="glyphicon glyphicon-shopping-cart"></span> BUY
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>



<br>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<% if @product.primary_image.attached? %>
                <%= image_tag @product.primary_image, class: "img-thumbnail", style: "max-height: 10rem;"%> 
                  <% end %>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Status:</strong>
  <%= @product.status %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @product.stock %>
</p>

<% if @product.images.attached? %>
    <% @product.images.each do |img| %>
        <%= image_tag img, class: "img-thumbnail", style: "max-height: 10rem;" %>
    <% end %>
<% end %>
<%= link_to 'Back', homes_path(@product) %>