config/routes.rb
Rails.application.routes.draw do
  resources :homes, only: [:index, :show]
  resources :orders
  root "homes#index"
  
  devise_for :admins
  match "/admins/products/delete_image/:id" => "admins/products#delete_image", via: :get
  namespace :admins do
    namespace :products do
      post 'csv_upload'
    end
  end

  namespace :admins do
    resources :products
    resources :categories
    resources :orders 
  end

end

app/models/product.rb
class Product < ApplicationRecord
    enum status: [:draft, :published, :archived]
    validates :stock, numericality: {greater_than_or_equal_to: 0}
    has_one_attached :primary_image
    has_many_attached :images
    has_many :product_categories, dependent: :destroy
    has_many :categories, through: :product_categories
end

app/controllers/admins/products_controller.rb
module Admins
  class ProductsController < ApplicationController
    before_action :set_product, only: %i[ show edit update destroy ]
    before_action :authenticate_admin!
    
    # GET /products or /products.json
    def index
      @products = Product.all

      respond_to do |format|
        format.html {}
        format.csv { send_data generate_csv(Product.all), file_name: 'product.csv' }
      end
    end

    # GET /products/1 or /products/1.json
    def show
      @products = Product.find(params[:id])
    end

    # GET /products/new
    def new
      @product = Product.new
      @category = Category.all
      @product_category = @product.product_categories.build
    end

    # GET /products/1/edit
    def edit
    end

    # POST /products or /products.json
    def create
      @product = Product.new(product_params)

      respond_to do |format|
        if @product.save
          format.html { redirect_to admins_product_path(@product), notice: "Product was successfully created." }
          format.json { render :show, status: :created, location: @product }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /products/1 or /products/1.json
    def update
      respond_to do |format|
        if @product.update(product_params)
          format.html { redirect_to admins_product_path(@product), notice: "Product was successfully updated." }
          format.json { render :show, status: :ok, location: @product }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /products/1 or /products/1.json
    def destroy
      @product.destroy
      respond_to do |format|
        format.html { redirect_to admins_products_path, notice: "Product was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    def csv_upload
      data = params[:csv_file].read.split("\n")
      data.each do |line|
        attr = line.split(",").map(&:strip)
        Product.create title: attr[0], description: attr[1], stock: attr[2]
      end
      redirect_to action: :index
    end

    def delete_image
      image = ActiveStorage::Attachment.find(params[:id])
      image.purge
      redirect_to action: :index
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_product
        @product = Product.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def product_params
        params.require(:product).permit(:title, :status, :description, :primary_image, :stock, category_ids: [], images: [])
      end

      def generate_csv(products)
        products.map { |a| [a.title, a.description, a.stock].join(',') }.join("\n")
      end
    
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!, except: [:index, :show]
  
  # GET /products or /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html
      format.csv { send_data generate_csv(Product.all), file_name: 'product.csv' }
    end
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @category = Category.all
    @product_category = @product.product_categories.build
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def csv_upload
    data = params[:csv_file].read.split("\n")
    data.each do |line|
      attr = line.split(",").map(&:strip)
      Product.create title: attr[0], description: attr[1], stock: attr[2]
    end
    redirect_to action: :index
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :status, :description, :stock, category_ids: [])
    end

    def generate_csv(products)
      products.map { |a| [a.title, a.description, a.stock].join(',') }.join("\n")
    end
  
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title %>
  </div>

  <div class="field">
    <%= form.label :status%>
    <%= form.select :status, Product.statuses.keys.map { |w| [w.humanize, w] } %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :stock %>
    <%= form.number_field :stock %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.collection_select(:category_ids,Category.all,:id,:name, {}, {multiple: true})%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<%= link_to 'Download CSV', products_path(format: :csv) %>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Status</th>
      <th>Description</th>
      <th>Stock</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.status %></td>
        <td><%= product.description %></td>
        <td><%= product.stock %></td>
        <td><%= product.categories.empty? ? 'NA' : product.categories.map(&:name).join(', ') %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>
<br>
<%= link_to 'New Category', new_category_path %>

<br>

<%= form_tag products_csv_upload_path, multipart: true do %>
  <%= file_field_tag :csv_file, class: 'file-input' %>
  <%= submit_tag :upload, class: 'button'%>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>